# Generated by Django 4.0.5 on 2022-07-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojapp', '0004_problem_input_problem_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='input',
            field=models.TextField(default=1, max_length=25000),
        ),
        migrations.AlterField(
            model_name='problem',
            name='output',
            field=models.TextField(default=1, max_length=25000),
        ),
    ]
