# Generated by Django 4.0.5 on 2022-07-08 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ojapp', '0006_problem_difficult_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='ppoint',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='score',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
