# Generated by Django 4.0.5 on 2022-07-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojapp', '0007_problem_ppoint_alter_score_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='solve',
            field=models.BooleanField(default=False),
        ),
    ]
