# Generated by Django 4.0.5 on 2022-07-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojapp', '0008_solution_solve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='difficult',
            field=models.CharField(max_length=25),
        ),
    ]
